### ISSUE TITLE
project name conflicts with directory and version structure 

### ISSUE THREAD

**Issue by brucellino** [SouthAfricaDigitalScience/geant4-deploy#2]
The project name is : `geant4`

however, the directory structure that is untarred from src is  `geant${VERSION}`, where ${VERSION} is one of the version variables, e.g. 4.10.3

The name of the project should be changed to `geant` instead of `geant4` (I don't think we'll be using geant3, so there shouldn't be any ambiguity)

**Comment by brucellino** [comment]
ok, so apparently there's a bit of problem between the naming schema and the url 

The URL for the source code wants `geant4/geant-$VERSION` which then untars to `geant$VERSION`, so either we chop off the "4", or we hard-code "geant" into the script instead of using ${NAME} and set name  back to geant4.

I did the latter

**Comment by bazinski** [comment]
pull request ?, alice still uses geant3, and there is an upcoming geant5

**Comment by brucellino** [comment]
then we can make different jobs for those - it would be tough to build all geant's in the same job - they're likely going to have different dependencies etc no ? I think you should consider them as different applications

**Comment by bazinski** [comment]
fair enough

**Comment by bazinski** [comment]
geant4 seperated from geant3
